### ISSUE TITLE
wrong email or password

### ISSUE THREAD

**Issue by cvandeplas** [csyezheng/edx-dl#5]
### Subject of the issue
Error during login

### Your environment
* Operating System (name/version): ubuntu 
* Python version: 3.11.6 
* youtube-dl version: installed automatically through pip dependency
* edx-helper version: latest git, installed through `pip install git+https://github.com/csyezheng/edx-helper.git`

### Steps to reproduce
```
$ edx-helper -u email   https://learning.edx.org/course/course-v1:EPFLx+DHA+2T2023
$ edx-helper -u email --list-courses
```
I also changed my password to something more simple.
Also tried with username instead of email.

### Expected behaviour
Be able to login. 

### Actual behaviour
```
$ edx-helper -u email   https://learning.edx.org/course/course-v1:EPFLx+DHA+2T2023
edx_helper version 0.6.4
Password: 
Building initial headers for future requests.
Getting initial CSRF token.
Found CSRF token.
Logging into Open edX site: https://courses.edx.org/login_ajax
Error, cannot login: HTTP Error 400: Bad Request
Wrong Email or Password.
```

**Comment by csyezheng** [comment]
@cvandeplas 

This seems to be due to too many failed login attempts and your edx account is locked, just try again later. This may take 30 minutes or an hour.

At this time, you can try to login at edx.org, but you probably won't be able to login either. This problem has nothing to do with this edx-helper.

If you can login at edx.org but cannot login using this download tool, please tell me.

[Why is my account locked?](https://support.edx.org/hc/en-us/articles/360033729293-Why-is-my-account-locked-)

**Comment by cvandeplas** [comment]
Hi, thanks for the prompt feedback. My account was not locked. I could log in perfectly through the website. I tried again today with a clean venv and I guess it must have been me doing something wrong, as it seems to work now. Sorry for the disturbance.
